Repository 2024-4lineton/FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#4 ✨ FEAT. 전통시장/전통시장 세부페이지, Nav바 제작
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/Nav/blackglobe.svg
  frontend/src/assets/Nav/blackpin.svg
  frontend/src/assets/Nav/blackuser.svg
  frontend/src/assets/Nav/grayglobe.svg
  frontend/src/assets/Nav/graypin.svg
  frontend/src/assets/Nav/grayuser.svg
  frontend/src/assets/TraditionalMarket/arrow.svg
  frontend/src/assets/TraditionalMarket/check.svg
  frontend/src/assets/TraditionalMarket/dropdown.svg
  frontend/src/assets/TraditionalMarket/market.svg
  frontend/src/assets/TraditionalMarket/market2.svg
  frontend/src/assets/TraditionalMarket/market3.svg
  frontend/src/assets/TraditionalMarket/market4.svg
  frontend/src/assets/TraditionalMarket/menu.svg
  frontend/src/entities/main/LastChanceContainer.jsx
  frontend/src/entities/main/MarketNav.jsx
  frontend/src/entities/traditionalMarket/detail/Market.jsx
  frontend/src/entities/traditionalMarket/detail/MarketDetailContent.jsx
  frontend/src/entities/traditionalMarket/detail/Menu.jsx
  frontend/src/entities/traditionalMarket/detail/Slider.jsx
  frontend/src/entities/traditionalMarket/detail/Title.jsx
  frontend/src/entities/traditionalMarket/main/List.jsx
  frontend/src/entities/traditionalMarket/main/MarketContent.jsx
  frontend/src/entities/traditionalMarket/main/MarketTitle.jsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/TraditionalMarket.jsx
  frontend/src/pages/TraditionalMarketDetail.jsx
  frontend/src/shared/components/Header.jsx
  frontend/src/shared/components/Nav.jsx
  frontend/src/shared/state/Market.js
Labels: ✨feat

#6 ✨ FEAT. 골목시장 페이지 추가
  frontend/src/App.js
  frontend/src/entities/main/MarketNav.jsx
  frontend/src/entities/streetMarket/Title.jsx
  frontend/src/entities/traditionalMarket/detail/Title.jsx
  frontend/src/pages/StreetMarket.jsx
  frontend/src/shared/components/Nav.jsx
Labels: ✨feat

#9 ✨ FEAT. 메뉴 세부 페이지 제작
  frontend/src/pages/MenuDetail.jsx
Labels: ✨feat

#11 ✨ FEAT. 메뉴 상세 페이지 - 모달창 구현
  frontend/src/assets/MenuDetail/success.svg
  frontend/src/entities/menuDetail/CartModal.jsx
  frontend/src/entities/menuDetail/ReservationModal.jsx
  frontend/src/pages/MenuDetail.jsx
Labels: ✨feat

#15 ✨ FEAT. 가게 등록 1차 UI 추가
  frontend/src/App.js
  frontend/src/assets/Header/profileIcon.svg
  frontend/src/assets/MarketRegistration/profileImg.svg
  frontend/src/entities/main/Footer.jsx
  frontend/src/pages/MarketRegistration.jsx
  frontend/src/shared/components/Header2.jsx
Labels: ✨feat

#17 🎨 STYLE. 디자인 수정 반영
  frontend/src/entities/main/MainComponent.jsx
  frontend/src/pages/StreetMarket.jsx
  frontend/src/pages/TraditionalMarketDetail.jsx
Labels: 🎨 style

#19 🎨 STYLE. Nav 위치 수정
  frontend/src/pages/StreetMarket.jsx
  frontend/src/shared/components/Nav.jsx
Labels: 🚑 hotfix, 🎨 style

#23 ✨ FEAT. 사업자 인증 페이지 추가
  frontend/.env
  frontend/src/assets/CompanyCertification/checkcircle.svg
  frontend/src/assets/CompanyCertification/infocircle.svg
  frontend/src/assets/CompanyCertification/shopIcon.svg
  frontend/src/pages/CompanyCertification.jsx
Labels: ✨feat

#25 ✨ FEAT. 판매글 등록 페이지 완성
  frontend/src/App.js
  frontend/src/assets/Sell/delete.svg
  frontend/src/assets/Sell/nullContainer.svg
  frontend/src/entities/sell/Modal.jsx
  frontend/src/pages/Sell.jsx
  frontend/src/shared/components/Header3.jsx
Labels: ✨feat

#29 Feature/#22 login page UI
  frontend/src/App.js
  frontend/src/assets/Login/HelFooMeBigLogo.svg
  frontend/src/assets/Login/google.svg
  frontend/src/assets/Login/kakao.svg
  frontend/src/assets/Login/naver.svg
  frontend/src/assets/Login/potato.svg
  frontend/src/entities/Login/LoginButton.js
  frontend/src/entities/Login/LoginCss.js
  frontend/src/entities/Login/TermsAgreeText.js
  frontend/src/pages/Login.js
  frontend/src/shared/animation/hoverGrow.jsx
Labels: ✨feat, 🎨 style

#31 ✨ FEAT. 커뮤니티 메인페이지 추가
  frontend/src/App.js
  frontend/src/assets/Community/arrow.svg
  frontend/src/assets/Community/article1.svg
  frontend/src/assets/Community/article2.svg
  frontend/src/assets/Community/article3.svg
  frontend/src/assets/Community/floating.svg
  frontend/src/assets/Community/heartIcon.svg
  frontend/src/assets/Community/messageIcon.svg
  frontend/src/entities/community/ArticleSlider.jsx
  frontend/src/entities/community/CommunityContent.jsx
  frontend/src/entities/community/Company.jsx
  frontend/src/entities/community/Free.jsx
  frontend/src/entities/community/New.jsx
  frontend/src/entities/community/Popular.jsx
  frontend/src/entities/community/Purchase.jsx
  frontend/src/entities/community/Sell.jsx
  frontend/src/entities/community/business/BusinessContent.jsx
  frontend/src/entities/community/business/NewPurchase.jsx
  frontend/src/entities/community/business/NewSell.jsx
  frontend/src/entities/community/business/PopularPurchase.jsx
  frontend/src/entities/community/business/PopularSell.jsx
  frontend/src/pages/Community.jsx
  frontend/src/shared/components/CommunityHeader.jsx
  frontend/src/shared/components/Nav.jsx
  frontend/src/shared/state/Community.js
Labels: ✨feat

#33 ✨ FEAT. 커뮤니티 상세 페이지 추가
  frontend/src/App.js
  frontend/src/entities/community/more/NewMore.jsx
  frontend/src/entities/community/more/PopularMore.jsx
  frontend/src/entities/community/more/PurchaseMore.jsx
  frontend/src/entities/community/more/SellMore.jsx
  frontend/src/pages/BusinessPurchaseMore.jsx
  frontend/src/pages/BusinessSellMore.jsx
  frontend/src/pages/CommunityNewMore.jsx
  frontend/src/pages/CommunityPopularMore.jsx
  frontend/src/shared/components/Nav.jsx
Labels: ✨feat

#36 Create custom API Hook
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/utils/Instance.jsx
Labels: ✨feat

#38 ✨ FEAT. 커뮤니티 글 작성 페이지 제작
  frontend/src/App.js
  frontend/src/assets/Community/camera.svg
  frontend/src/entities/community/CommunityContent.jsx
  frontend/src/entities/main/Article.jsx
  frontend/src/entities/main/Articlecontent.jsx
  frontend/src/entities/main/Dashboard.jsx
  frontend/src/pages/BusinessPurchaseMore.jsx
  frontend/src/pages/BusinessSellMore.jsx
  frontend/src/pages/Community.jsx
  frontend/src/pages/CommunityNewMore.jsx
  frontend/src/pages/CommunityPopularMore.jsx
  frontend/src/pages/CommunityWriting.jsx
  frontend/src/pages/MenuDetail.jsx
Labels: ✨feat

#41 ✨FEAT. Kakao Login 70%
  frontend/.env
  frontend/src/apis/api/login.js
  frontend/src/entities/Login/LoginButton.js
Labels: ✨feat

#45 ✨ FEAT. 팔아요 세부페이지 추가
  frontend/src/App.js
  frontend/src/assets/Community/call.svg
  frontend/src/assets/Community/heart.svg
  frontend/src/entities/sell/ConfirmationModal.jsx
  frontend/src/entities/sell/SellReservationModal.jsx
  frontend/src/pages/SellDetail.jsx
Labels: ✨feat

#47 ✨FEAT. Complete Kakao Login
  frontend/src/pages/Main.jsx
Labels: ✨feat

#48 Feature/#43 add info 1
  frontend/src/App.js
  frontend/src/apis/api/login.js
  frontend/src/apis/api/user.js
  frontend/src/apis/utils/Instance.jsx
  frontend/src/assets/AddInfo/HelFooMeSmallLogo.svg
  frontend/src/assets/AddInfo/defaultProfileImg.svg
  frontend/src/entities/addInfo/AddInfoFrame.js
  frontend/src/entities/addInfo/AddInfoHeader.js
  frontend/src/entities/addInfo/AddInfoStyle.js
  frontend/src/entities/addInfo/ProfileImg.js
  frontend/src/index.js
  frontend/src/pages/Main.jsx
  frontend/src/pages/addInfoPage/AddInfoPage1.js
Labels: ✨feat

#50 ✨FEAT. AddInfoPage Frame Complete
  frontend/src/entities/addInfo/AccountModify.js
  frontend/src/entities/addInfo/AddInfoFrame.js
  frontend/src/entities/addInfo/AddInfoNextButton.js
  frontend/src/entities/addInfo/AddInfoStyle.js
  frontend/src/entities/addInfo/LogOut.js
  frontend/src/pages/addInfoPage/AddInfoPage1.js
Labels: ✨feat

#52 ✨ FEAT. 마이페이지 추가
  frontend/src/assets/MyPage/pen.svg
  frontend/src/entities/mypage/Company.jsx
  frontend/src/entities/mypage/Normal.jsx
  frontend/src/pages/MyPage.jsx
Labels: ✨feat

#56 ✨FEAT. MainPage Connect API Complete
  frontend/src/entities/main/Article.jsx
  frontend/src/entities/main/Articlecontent.jsx
  frontend/src/entities/main/LastChance.jsx
  frontend/src/entities/main/LastChanceContainer.jsx
  frontend/src/entities/main/Recommend.jsx
  frontend/src/entities/main/RecommendContainer.jsx
  frontend/src/pages/Main.jsx
  frontend/src/shared/state/token.js
Labels: ✨feat

#58 ✨ FEAT. 판매 내역 페이지 추가
  frontend/src/App.js
  frontend/src/assets/MyPage/floating.svg
  frontend/src/assets/MyPage/star.svg
  frontend/src/entities/mypage/List.jsx
  frontend/src/entities/mypage/Now.jsx
  frontend/src/entities/mypage/Prev.jsx
  frontend/src/entities/mypage/PrevList.jsx
  frontend/src/pages/SellList.jsx
  frontend/src/shared/components/Nav.jsx
Labels: ✨feat

#60 ✨ FEAT. 판매자 메뉴 상세 페이지 추가
  frontend/src/App.js
  frontend/src/entities/sell/ReservationList.jsx
  frontend/src/pages/MenuDetail.jsx
  frontend/src/pages/SellerDetail.jsx
Labels: ✨feat

#61 Feature/#57 market api
  frontend/src/apis/api/productList.js
  frontend/src/entities/traditionalMarket/detail/MarketDetailContent.jsx
  frontend/src/entities/traditionalMarket/detail/Menu.jsx
  frontend/src/entities/traditionalMarket/main/List.jsx
  frontend/src/entities/traditionalMarket/main/MarketContent.jsx
  frontend/src/entities/traditionalMarket/main/MarketTitle.jsx
  frontend/src/pages/Brand.jsx
  frontend/src/pages/StreetMarket.jsx
Labels: ✨feat

#63 :sparkles: FEAT. 알림 기능 추가, favicon 변경
  frontend/public/favicon.ico
  frontend/src/App.js
  frontend/src/assets/Header/noti.svg
  frontend/src/entities/notification/List.jsx
  frontend/src/entities/notification/Noti.jsx
  frontend/src/entities/notification/PrevList.jsx
  frontend/src/pages/MenuDetail.jsx
  frontend/src/pages/Notification.jsx
  frontend/src/shared/components/Header.jsx
  frontend/src/shared/components/Nav.jsx
  frontend/src/shared/state/Noti.js
Labels: ✨feat

#64 Feature/#42 add info page 2 3
  frontend/.env
  frontend/src/App.js
  frontend/src/assets/AddInfo/areaIcon.svg
  frontend/src/assets/AddInfo/checkedIcon.svg
  frontend/src/assets/AddInfo/nonCheckIcon.svg
  frontend/src/entities/addInfo/AddInfoFrame.js
  frontend/src/entities/addInfo/AddInfoNextButton.js
  frontend/src/entities/addInfo/ProfileImg.js
  frontend/src/pages/addInfoPage/AddInfoPage1.js
  frontend/src/pages/addInfoPage/AddInfoPage2.js
  frontend/src/pages/addInfoPage/AddInfoPage3.js
  frontend/src/shared/state/token.js
  frontend/src/shared/state/userInfo.js
Labels: ✨feat
